### ISSUE TITLE
ZeroDivisionError

### ISSUE THREAD

**Issue by fatihsucu** [muatik/genderizer#2]
If genderizer takes an text argument like below;

```
Tavla oynamayı bilmeyen erkek gitsin örgü örsün amk  Bu akşam konuşamadık 😦  Yaz geldi siz hala kış masalı şarkısını paylasıyorsunuz yeter yani  Erkek adam form yiyip formda kalmaz  Uyku diye meslek olsa mesaiye bile kalırım  Şimdi gitme vakti geldi burası son durak  Doğan güneş Bandırma 😊  Radu feat Sefir &amp; Farabi - Elveda: http://t.co/OKNGfoR3xV @YouTube aracılığıyla  Ben hala küçük bir çocuk  http://t.co/AwoTqKAqGK  
RT @saptroloji: BALIK: Balık burcuyla başa çıkabileceğinizi sanıyorsanız yanılıyorsunuz. Boşuna uğraşmayın.  Bundan sonra tarih derslerini kaçırmak yok  Tek yapacağın şey ilgilenmekti aslında  Gördüm yine kötü oldum  Let The games begin 😄  Canımız bira isterse sipariş ederiz kapımıza gelir hizmette sınır yok 😀  
Senin için mücadele etmeyen biri, doğru kişi olamaz  ? http://t.co/n9wh7t7af0  Biri bizim kafaları kargoyla bursa yollayabilr mi ?  Bizi biliyon, boktan insanlara alışıyoz 
```

``` python
#detect gives an  error like this
classifierScoreLogF = probablities['female'] / sum(probablities.values())
#ZeroDivisionError: float division by zero 
```

**Comment by nejdetckenobi** [comment]
That's a truncation (underflow) error which should be solved. The "default probability" (1e-8 approximately) is used, when your word not in the entire training set. When a word can not be found in all classes, we set its probability to default probability to avoid the "ZeroDivisionError". 
But when multiple words can not be found in entire training set, they'll be the terms of a multiplication which means the probability is getting smaller with a significant speed (last non-zero term is 1e-324). We should set probability to 1 (which will be multiplied) if the token is not found in entire training set or pass that token. 
Because we don't get any information for that token. So the probability shouldn't be changed.

**Comment by muatik** [comment]
This issue belongs to the text classifier, not directly of Genderizer. Currently https://github.com/muatik/naive-bayes-classifier is adopted as a text classifier.

I fixed the issue in the classifier's repository https://github.com/muatik/naive-bayes-classifier/commit/eeb80b24cf13775bc73086a734c0ff5594e2a662

**Comment by HenkPoley** [comment]
Bug still/again happens on current git master with input 'Felienne':

```python
>>> print Genderizer.detect(text='Felienne')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "genderizer/genderizer.py", line 82, in detect
    classifierScoreLogF = probablities['female'] / sum(probablities.values())
ZeroDivisionError: float division by zero
```
